### ISSUE TITLE
adjust the reverse proxy to the new port and https protocol in the local connection of jitsi

### ISSUE THREAD

**Issue by ghost** [immanuelfodor/immanuelfodor#2]
hello, i am doing research on jitsi and got some error need to adjust reverse proxy to new port and https protocol in jitsi local connection (https->proxy->http:8000->jitsi becomes https->proxy->https:8443->jitsi). someone help me please!!

**Comment by immanuelfodor** [comment]
Hi, I think you should ask this question in some Jitsi repos then

**Comment by ghost** [comment]
excuse me,I read in your article about jitsi that you used this method to fix jitsi failed to connect error before. so i wish you could show me your way

**Comment by immanuelfodor** [comment]
Could you please link me that article to let me get context?

**Comment by ghost** [comment]
this is here: https://github.com/jitsi/docker-jitsi-meet/issues/11

**Comment by immanuelfodor** [comment]
Wow, that was like 4 years ago, I don't even have that VM running anymore, I'm not even sure if they have updated anything or not in the meantime. From the last comment, it had something to do with the reverse proxy in front of Jitsi, I needed to use the https port of the Jitsi docker compose stack instead of the http one to make webrtc work, so every communication should be over https finally.
